server:
  port: 52001
  # 设置数据压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,text/css,text/plain,application/javascript,application/json,application/xml


spring:
  application:
    name: mousika-sea-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 当本队使用uat app 服务的时候这个不能开，如果开了会直接找dev注册中心上的app服务
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: dev

logging:
  level:
    ROOT: INFO
#logging:
#  level:
#    com.alibaba.cloud.nacos.refresh: debug

